# Generated by Django 3.0.4 on 2020-03-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic2user',
            options={'verbose_name': '题目用户对应关系', 'verbose_name_plural': '题目用户对应关系'},
        ),
        migrations.AlterModelOptions(
            name='topicrecord',
            options={'verbose_name': '题目', 'verbose_name_plural': '题目'},
        ),
        migrations.AlterField(
            model_name='topicrecord',
            name='accept',
            field=models.SmallIntegerField(choices=[(0, '等待命题老师和教学秘书确认中'), (1, '命题教师已确认选题，等待教秘确认'), (2, '选题通过')], default=0, verbose_name='确认状态'),
        ),
        migrations.AlterField(
            model_name='topicrecord',
            name='chosen_num',
            field=models.SmallIntegerField(default=0, verbose_name='已选人数'),
        ),
    ]
