# Generated by Django 3.0.4 on 2020-04-10 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0003_auto_20200409_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annex',
            name='detail',
        ),
    ]
